There is an increasing loss of jobs in the midst of high unemployment in South Africa as a result of the 4IR and more recently COVID. It is therefore necessary to recommend policy that is based on evidence (data). If we do not take such an evidence-based approach to innovation, we will be repeating the same mistakes over again. The environment today is rapidly changing and the same needs to apply to policy.

In [2]:
import numpy as np
import pandas as pd 
import time
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, classification_report, confusion_matrix

In [12]:
data = pd.read_excel('./Limpopo Province data/Individual health and socio economic data.xlsx')

In [15]:
data

,IndividualId,Gender,DateOfBirth,ObservationDate,MotherStatus,FatherStatus,CurrentEducation,HighestSchoolLevel,HighestNonSchoolLevel,CurrentEmployment,...,BPDiastolic3,Pulse3,HIVEverTested,HIVEverNegTest,HIVLastNegTest,HIVEverPostTest,HIVFirstPostTest,ARTEver,ARTStarted,ARTCurrent
0,1.0,1.0,1997-05-29,2019-04-20 00:00:00,0.0,0.0,3.0,12.0,-1.0,0.0,...,91.0,53.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,1.0,1960-06-24,2017-09-30 00:00:00,0.0,0.0,-1.0,-1.0,-1.0,0.0,...,NaN,NaN,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN
2,3.0,2.0,1996-07-19,2020-06-25 00:00:00,0.0,0.0,3.0,-1.0,21.0,0.0,...,106.0,89.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN
3,4.0,2.0,1930-06-10,2020-02-06 00:00:00,0.0,0.0,3.0,-1.0,98.0,0.0,...,96.0,67.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,1.0,1962-12-07,2019-12-03 00:00:00,0.0,0.0,3.0,-1.0,98.0,0.0,...,91.0,86.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9187,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9188,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9189,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9190,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9191,NaN,NaN,NaT,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN